### ISSUE TITLE
Chapter 7: Bad cop unclear what exactly is not ok

### ISSUE THREAD

**Issue by willemvdb42** [matheusfacure/python-causality-handbook#82] opened 2021-05-16 13:59 UTC
In chapter 7, under section "bad cop", it's not clear to me what the mistake is exactly. Is it that the equality:
E[Y_i | T_i] = E[Y_i | Y_i > 0, T_i] * P(Y_i > 0 | T_i)
does not hold? This looks like an application of the law of total probability to me, so I'm not sure where the mistake is? If this equality indeed does not hold, I would strongly advise explicitly stating that in the text with an explanation of why not.

If however this equality is correct, then it's not at all clear to me what the mistake is that the text is warning about. The worked example that follows is extremely vague, in that it makes a reference to the selection bias term we calculated. But as we can see in the math above, there are a lot more terms to be considered when calculating the causal effect that way. So as long as we calculate all of these, it looks to me like there is no problem. 

In any case I really like chapter 7 in general as it gives a lot of intuition about what to do and what not to do. Only this bad cop part needs some more explicit clarification (at least for me).

**Comment by matheusfacure** [comment] 2021-05-16 18:58
Bad cop is rely hard to wrap my head around it. I'll try to explain it here while I come up with a better example.  It is not that the equality is wrong. This is a mathematical truth:
```
E[Y_i | T_i] = E[Y_i | Y_i > 0, T_i] * P(Y_i > 0 | T_i)
```
The problem is that `E[Y | Y > 0, T]` cannot be causaly estimated. Think of is this way: some people are zeros only because they didn't got the treatment. If they had gotten the treatment, then they would **not** be zeros (one example of this is when T is a sales campaign and Y is amount bought). On the other hand, other people are never zero (in the sales example, they always buy something, even without the campaign). It's not hard to imagine that those who go from zero to not zero with the treatment have a lower baseline Y (lower Y0) than those that are always not zero (in the sales example, they are poorer, so they only buy with sales). Which means that, once you exclude the zeros, `E[Y | Y > 0, T=0]` will not have any of those folks with low baseline Y (because under no treatment, they are zero, and you've removed them), which will inflate your estimate of `E[Y | Y > 0, T=0]`. On the flip side, they will appear in your estimate of  `E[Y| Y> 0, T=1]` (on the sales example, they DO with the sales treatment). 
The end result is that `E[Y | Y > 0, T=0]` will be inflated, making the difference `E[Y | Y > 0, T = 0] - E[Y | Y > 0, T=1]` downward biased.

**Comment by willemvdb42** [comment] 2021-05-17 09:41
Ok, I think I understand the confusion now. Your point is really that you cannot estimate the causal effect by looking _only_ at `E[Y | Y > 0, T = 1] - E[Y | Y > 0, T=0]`, because this has a selection bias because of the filter on `Y > 0`. But if I understand correctly it's still correct to use the full form:
`E[Y | Y > 0, T = 1] * P(Y > 0 | T = 1) - E[Y | Y > 0, T = 0] * P(Y > 0 | T = 0)`
correct?

In this case I would suggest to more explicitly mention this in the text: state that it's ok to use the full form, but not the shorter one where you only look at `E[Y | Y > 0, T = t]`. The mathematical derivation you already have shows this quite nicely. (And I think this is probably what you meant to say there as well.) I would just word it a bit more explicitly in the text: "Hence one cannot derive the causal effect from the CoP term alone. So it is ok to use this split into two parts, so long as you use both parts to derive the causal effect: `E[Y | Y > 0, T = 1] * P(Y > 0 | T = 1) - E[Y | Y > 0, T = 0] * P(Y > 0 | T = 0)`."

Just my 2 cents.

**Comment by matheusfacure** [comment] 2021-05-17 20:06
I think I can make it more clearly indeed. Thks for the feedback.

**Comment by matheusfacure** [comment] 2021-05-19 23:56
PR #83 should address this

**Closed** 2021-05-20 11:36 UTC
